"""Broader small/mid-cap roster across regions for accumulation scan.

Approximately 350 additional tickers across:
  - Russell 2000 / S&P SmallCap 600 names not in our prior sweeps
  - UK AIM-listed small caps with M&A or activist potential
  - European mid-caps with recent governance change
  - Canadian TSX value names
  - Australian ASX small caps with takeover history

Curated, not exhaustive -- focus on names that:
  (a) sit in event-driven hunting grounds (industrials, retailers,
      asset managers, biotech, special-sit holdcos)
  (b) have had 13D / activist / RSA / wind-down history at some point
  (c) are sized so a 5x volume spike is meaningful (>$30M ADV)
"""

BROADER_UNIVERSE = [
    # ===== Russell 2000 / S&P SmallCap event-driven names =====
    # Activist-magnet small caps (event-driven historicals)
    "ACU", "AIN", "AKAM", "AKO-A", "ALDX", "ALGT", "ALSN", "AMBC", "AMC",
    "AMR", "AMRX", "ANGO", "AOSL", "APEI", "APLD", "ARDX", "ARI", "ARLO",
    "ARRY", "ARWR", "ASAN", "ASIX", "ATRO", "ATSG", "AVAH", "AVD", "AVNS",
    "AXTI", "AXSM", "AZZ", "BBSI", "BCC", "BCRX", "BDC", "BFC", "BFLY",
    "BFS", "BGFV", "BHB", "BHE", "BHF", "BHLB", "BJRI", "BKE", "BLBD",
    "BLFS", "BLMN", "BLNK", "BLU", "BNED", "BNRG", "BOOM", "BOOT", "BOX",
    "BPMC", "BRT", "BSIG", "BTU", "BUSE", "BV", "BVH", "BWB", "BWMN", "BXC",
    "BY", "BZH", "CALM", "CALX", "CARG", "CARS", "CASS", "CASY", "CATO",
    "CATY", "CBRL", "CBT", "CBU", "CC", "CCB", "CCBG", "CCL", "CCLD",
    "CCNE", "CCOI", "CDXC", "CDZI", "CENT", "CENTA", "CERT", "CFB",
    "CFG", "CFR", "CGNT", "CHCO", "CHCT", "CHDN", "CHE", "CHEF", "CHGG",
    "CHK", "CHRW", "CHWY", "CIM", "CIO", "CION", "CIVB", "CIVI", "CKX",
    "CLDT", "CLF", "CLNE", "CLWT", "CMC", "CMCM", "CMRE", "CMTL", "CNS",
    "CNTY", "COCO", "CODI", "COHU", "COLB", "COMM", "CONE", "COOP", "COR",
    "CORT", "CRH", "CRSP", "CSGP", "CSWI", "CTAS", "CTLP", "CTOS", "CTRE",
    "CUBI", "CUE", "CUTR", "CVCO", "CVI", "CVLT", "CVRX", "CWBC", "CWH",
    "CWST", "CXM", "CXT", "CYBR", "CYCN", "CYH",
    # Industrials / retail special-sit
    "DENN", "DESP", "DGII", "DH", "DHIL", "DIN", "DISH", "DJCO", "DK",
    "DKL", "DLB", "DNB", "DOC", "DOCS", "DOMA", "DOMO", "DOOR", "DOX",
    "DRH", "DRVN", "DSEY", "DSGN", "DSP", "DTC", "DTE", "DTM", "DTSS",
    "DV", "DVAX", "DXC", "DY", "DYAI", "EARN", "EAT", "EB", "EBC",
    "EBIX", "EBS", "EBTC", "EBYX", "ECAT", "ECC", "EDIT", "EFC", "EFOI",
    "EGAN", "EGBN", "EGHT", "EGY", "EHC", "EIG", "EIX", "EKSO", "ELME",
    "ELP", "EMBC", "EME", "EMKR", "EMN", "ENG", "ENIC", "ENS", "ENSV",
    "ENTA", "ENTG", "ENV", "ENVA", "ENVX", "EOLS", "EPC", "EPM", "EPR",
    "EQRX", "ERIE", "ERJ", "ESEA", "ESLT", "ESPR", "ESTC", "ETD",
    "ETON", "EURN", "EVA", "EVBG", "EVC", "EVI", "EVRI",
    # Healthcare / biotech mids
    "FATE", "FBP", "FCEL", "FCN", "FCPT", "FELE", "FEN", "FET", "FF",
    "FFIN", "FHN", "FIBK", "FIVN", "FIXX", "FL", "FLR", "FLY", "FNB",
    "FNF", "FNKO", "FOLD", "FORM", "FORR", "FOXF", "FRBA", "FREE", "FRG",
    "FRLN", "FRSH", "FSP", "FSR", "FSTR", "FTAI", "FTRE", "FUL", "FULC",
    "FUN", "FWRD", "FYBR", "GBX", "GCI", "GCT", "GDEN", "GDOT", "GDRX",
    "GDS", "GEC", "GEF", "GEO", "GEVO", "GFF", "GHC", "GHG", "GHM",
    "GIII", "GILT", "GLDD", "GLNG", "GLOB", "GLPI", "GMS", "GNK", "GNRC",
    "GNS", "GO", "GOEV", "GOSS", "GPRO", "GPS", "GRBK", "GRC", "GREE",
    "GRMN", "GRPN", "GSAT", "GSBC", "GSHD", "GTBP", "GTHX", "GTLB", "GTLS",
    "GTX", "GVA", "GWB", "GWRE", "GWRS", "GXO", "HAIN", "HALO", "HASI",
    "HBT", "HCAT", "HCC", "HCSG", "HEAR", "HEES", "HEI-A", "HEPS", "HFFG",
    "HHH", "HI", "HIBS", "HIMS", "HIPO", "HLI", "HLT", "HOFT", "HOLX",
    "HOMB", "HOOD", "HP", "HPK", "HPP", "HQI", "HQY", "HR", "HRB",
    "HRI", "HSAI", "HSC", "HST", "HTLD", "HUBG", "HUMA", "HURN", "HVT",
    "HWC", "HWM", "HY", "HYFM", "IAC", "IART", "IAS", "IBOC", "IBP",
    "IBRX", "ICCC", "ICHR", "ICUI", "IDEX", "IDR", "IDT", "IEX", "IFRX",
    "IGT", "IHRT", "IIIN", "IIPR", "ILPT", "IMAX", "IMVT", "INDB", "INFA",
    "INMD", "INNV", "INO", "INSE", "INSG", "INSM", "INSP", "INSW", "INVA",
    "INVE", "INVH", "INZY", "IONQ", "IOSP", "IOVA", "IPDN", "IPI", "IPSC",
    "IRBT", "IRIX", "IRMD", "IRT", "IRTC", "IRWD", "ISIN", "ISO",

    # ===== UK AIM 100 / AIM 50 small caps =====
    # Notable AIM names with M&A or activist history
    "AAA.L", "ABDP.L", "AEA.L", "AFE.L", "AGY.L", "AIE.L", "AJB.L",
    "ANG.L", "ANP.L", "AO.L", "APAX.L", "ARC.L", "ARGO.L", "ARS.L",
    "ASTO.L", "ATG.L", "ATY.L", "AUTG.L", "AUTO.L", "AV.L", "BARK.L",
    "BBOX.L", "BCG.L", "BEMS.L", "BFM.L", "BG.L", "BGEU.L",
    "BHMG.L", "BIDS.L", "BIRG.L", "BMS.L", "BMY.L", "BOO.L", "BOOM.L",
    "BPMC.L", "BSF.L", "BUR.L", "BVS.L", "BVXP.L", "BYIT.L", "BZM.L",
    "CARD.L", "CAY.L", "CCJI.L", "CCT.L", "CDFF.L", "CDX.L", "CER.L",
    "CGS.L", "CHRT.L", "CHRY.L", "CKN.L", "CLIG.L", "CMCL.L", "CMCX.L",
    "CMV.L", "CNCT.L", "CNIC.L", "COCO.L", "COG.L", "CPI.L", "CPP.L",
    "CRDA.L", "CREO.L", "CTH.L", "CTO.L", "CUSN.L", "CVSG.L", "CWR.L",
    "DARK.L", "DAVS.L", "DCC.L", "DEC.L", "DGNS.L", "DGOC.L", "DLG.L",
    "DSCV.L", "DSW.L", "DUKE.L", "DXSP.L", "EAAS.L", "EBQ.L", "ECEL.L",
    "ECT.L", "ECV.L", "EFG.L", "EJF.L", "EKF.L", "EKT.L", "EMR.L",
    "ENGI.L", "ENOG.L", "ENQ.L", "ENT.L", "ERM.L", "ESL.L", "ESNT.L",
    "ETO.L", "EXPN.L", "EYE.L", "EZJ.L", "FAB.L", "FCX.L", "FDM.L",
    "FEET.L", "FEN.L", "FERG.L", "FEVR.L", "FFI.L", "FGP.L", "FIN.L",
    "FRAS.L", "FRES.L", "FRP.L", "FUL.L", "FUM.L", "FUTR.L", "FXPO.L",
    "GAMA.L", "GAW.L", "GBG.L", "GCM.L", "GEMD.L", "GFTU.L", "GHE.L",
    "GHH.L", "GHL.L", "GLEN.L", "GLG.L", "GMS.L", "GMX.L", "GNS.L",
    "GOAL.L", "GOG.L", "GOOD.L", "GROW.L", "GRP.L", "GRX.L",
    "GSF.L", "GSS.L", "GUS.L", "HALN.L", "HAS.L", "HBR.L", "HCFT.L",
    "HFG.L", "HG.L", "HGM.L", "HIK.L", "HIPG.L", "HIVE.L", "HMSO.L",
    "HOC.L", "HUR.L", "HWG.L", "HZD.L", "IAG.L", "IBTF.L", "ICG.L",
    "ICGT.L", "ICP.L", "IDS.L", "IGP.L", "IHC.L", "IHG.L", "IHP.L",
    "IIG.L", "IMI.L", "INCH.L", "INF.L", "INFA.L", "INSE.L", "INSP.L",
    "INTU.L", "INV.L", "INVE.L", "IPF.L", "IPO.L", "IPX.L", "IQE.L",
    "ITM.L", "ITRK.L", "IWG.L", "JAY.L", "JD.L", "JDG.L",
    "JESO.L", "JET2.L", "JMG.L", "JOIN.L", "JSE.L", "KAPE.L", "KDR.L",
    "KEYS.L", "KGH.L", "KIE.L", "KITW.L", "KMR.L", "KNOS.L", "LAB.L",
    "LARK.L", "LBOW.L", "LIO.L", "LION.L", "LMP.L", "LNG.L", "LRE.L",
    "LSEG.L", "LST.L", "LSTV.L", "LTHM.L", "LUCE.L", "LWB.L", "MAB1.L",
    "MAB.L", "MACU.L", "MAB1.L", "MAGP.L", "MARS.L", "MCB.L", "MCG.L",
    "MERL.L", "MGAM.L", "MGNS.L", "MGP.L", "MICRO.L", "MKS.L", "MLA.L",
    "MMC.L", "MMP.L", "MNG.L", "MNI.L", "MNL.L", "MORG.L", "MPE.L",
    "MROZ.L", "MRVI.L", "MSI.L", "MSLH.L", "MTC.L", "MTRO.L", "MTW.L",
    "MUR.L", "MUSA.L", "MYI.L", "NAS.L", "NESS.L", "NEXS.L", "NICL.L",
    "NLG.L", "NOG.L", "NOP.L", "NWF.L", "NWG.L", "NWT.L", "NXR.L",

    # ===== Canadian TSX / TSXV small caps =====
    "AC.TO", "AGI.TO", "AOI.TO", "ARE.TO", "ARG.TO", "ATA.TO", "ATD.TO",
    "ATH.TO", "ATP.TO", "AUR.TO", "AYR.TO", "BCB.TO", "BDT.TO", "BEK.TO",
    "BIR.TO", "BITF.TO", "BLDP.TO", "BLN.TO", "BLO.TO", "BLX.TO", "BNS.TO",
    "BTO.TO", "CCL-B.TO", "CG.TO", "CIA.TO", "CIO.TO", "CIX.TO",
    "CJ.TO", "CMG.TO", "CNQ.TO", "COR.TO", "CPG.TO", "CPL.TO", "CPX.TO",
    "CRH.TO", "CRR-UN.TO", "CSU.TO", "CSW-A.TO", "CTC-A.TO",
    "CTS.TO", "DGM.TO", "DHT.TO", "DML.TO", "DOC.TO", "DOL.TO", "DPM.TO",
    "DRT.TO", "DSG.TO", "ECN.TO", "ECO.TO", "EFR.TO", "EFX.TO", "EIF.TO",
    "ENB.TO", "ENGH.TO", "EQX.TO", "ERF.TO", "FFH.TO", "FM.TO", "FMG.TO",
    "FN.TO", "FNV.TO", "FR.TO", "FSV.TO", "FTS.TO", "GIB-A.TO",
    "GMG.TO", "GOOS.TO", "HAI.TO", "HBM.TO", "HCG.TO", "HEXO.TO",
    "HOM-UN.TO", "IMG.TO", "IMV.TO", "K.TO", "KEL.TO", "KEY.TO",
    "KMP-UN.TO", "KNT.TO", "KSI.TO", "L.TO", "LAS-A.TO", "LIO.TO",
    "MEG.TO", "MFC.TO", "MIM.TO", "MNT.TO", "MRE.TO", "MRG-UN.TO",
    "MRU.TO", "MX.TO", "NA.TO", "NCAN.TO", "NEO.TO", "NEXT.TO", "NPI.TO",
    "NTR.TO", "NVA.TO", "NXR-UN.TO", "OBE.TO", "OGN.TO", "ONC.TO",
    "OPS.TO", "OR.TO", "OVV.TO", "PAAS.TO", "PD.TO", "PEY.TO", "PIF.TO",
    "PKI.TO", "PLZ-UN.TO", "POU.TO", "POW.TO", "PPL.TO", "PRMW.TO",
    "PXT.TO", "QBR-B.TO", "QSR.TO", "RBA.TO", "RBN-UN.TO", "RCH.TO",
    "RCI-B.TO", "REI-UN.TO", "RHC-A.TO", "RIO.TO", "RNW.TO", "RUS.TO",
    "RY.TO", "SAP.TO", "SES.TO", "SGRO.TO", "SHOP.TO", "SIA.TO", "SII.TO",
    "SJ.TO", "SLF.TO", "SLS.TO", "SMU-UN.TO", "SOY.TO", "SPB.TO",
    "STN.TO", "SU.TO", "SVI.TO", "SVM.TO", "T.TO", "TCS.TO", "TCN.TO",
    "TD.TO", "TFII.TO", "THX.TO", "TIH.TO", "TIXT.TO", "TKO.TO", "TLO.TO",
    "TOU.TO", "TPX-A.TO", "TRI.TO", "TRP.TO", "TXG.TO", "U-UN.TO",
    "URE.TO", "VFF.TO", "VLN.TO", "VMD.TO", "VRX.TO", "WCN.TO", "WCP.TO",
    "WDO.TO", "WEED.TO", "WFG.TO", "WJX.TO", "WN.TO", "WPK.TO", "WPM.TO",
    "WSP.TO", "X.TO", "Y.TO", "YRI.TO",

    # ===== Australian ASX small caps =====
    "A2M.AX", "ABB.AX", "ABC.AX", "ABG.AX", "ADH.AX", "AGL.AX", "ALD.AX",
    "ALL.AX", "ALQ.AX", "AMC.AX", "ANN.AX", "ANZ.AX", "APX.AX", "ARB.AX",
    "ARG.AX", "AST.AX", "ATM.AX", "AVH.AX", "AX1.AX", "AXP.AX", "BBN.AX",
    "BBT.AX", "BEN.AX", "BFG.AX", "BHP.AX", "BIN.AX", "BKL.AX", "BKW.AX",
    "BPT.AX", "BRG.AX", "BSL.AX", "BUB.AX", "BVS.AX", "CAJ.AX", "CAR.AX",
    "CCP.AX", "CCX.AX", "CDA.AX", "CGC.AX", "CGF.AX", "CIA.AX", "CKF.AX",
    "CLW.AX", "CMW.AX", "CMM.AX", "CNI.AX", "COE.AX", "COL.AX", "CPU.AX",
    "CQR.AX", "CSL.AX", "CSR.AX", "CTD.AX", "CWY.AX", "CYL.AX", "DDR.AX",
    "DDH.AX", "DEG.AX", "DJW.AX", "DLI.AX", "DMP.AX", "DRR.AX", "DTL.AX",
    "DXC.AX", "DXS.AX", "EBO.AX", "EHE.AX", "ELD.AX", "ENN.AX", "ERA.AX",
    "EVN.AX", "FBU.AX", "FLT.AX", "FMG.AX", "FXL.AX", "GMG.AX", "GNC.AX",
    "GOR.AX", "GPT.AX", "GUD.AX", "GWA.AX", "HMC.AX", "HUB.AX", "HVN.AX",
    "ICR.AX", "IFL.AX", "IGO.AX", "ILU.AX", "IMD.AX", "INA.AX", "INR.AX",
    "IPL.AX", "IRE.AX", "JBH.AX", "JHX.AX", "JIN.AX", "JLG.AX", "JRV.AX",
    "KAR.AX", "KGN.AX", "KMD.AX", "KSL.AX", "LCK.AX", "LIC.AX", "LLC.AX",
    "LNK.AX", "LOV.AX", "LYC.AX",

    # ===== European mid-caps =====
    "ABBN.SW", "ADYEN.AS", "ADS.DE", "AENA.MC", "AHT.L",
    "ALO.PA", "ATCO-A.ST", "ATL.MI", "BBVA.MC", "BIM.PA",
    "BME.MC", "BMW.DE", "BN.PA", "BNP.PA", "BVI.PA",
    "CABK.MC", "CAP.PA", "CON.DE", "CRG.IR", "CS.PA",
    "DG.PA", "DTG.DE", "DWNI.DE", "EAB.MC", "EBS.VI",
    "EDP.LS", "EI.PA", "ELE.MC", "ENEL.MI", "ENI.MI",
    "FER.MC", "FORTUM.HE", "FR.PA", "GLE.PA", "G.MI",
    "HEI.DE", "HEN3.DE", "HFG.DE", "IAG.MC", "IBE.MC",
    "IFX.DE", "ITX.MC", "KNEBV.HE", "KER.PA", "LDO.MI",
    "LHA.DE", "LISN.SW", "LR.PA", "MBG.DE", "MC.PA", "MTX.DE",
    "NESTE.HE", "NN.AS", "NOKIA.HE", "NOVO-B.CO", "NTGY.MC",
    "OCDO.L", "OMV.VI", "ORA.PA", "PHIA.AS", "PNDORA.CO",
    "PROX.BR", "PUM.DE", "RACE.MI", "RBI.VI", "RDSB.L",
    "RHM.DE", "RI.PA", "RKT.L", "RWE.DE", "SAB.MC",
    "SAF.PA", "SAN.MC", "SAP.DE", "SBO.VI", "SCA-B.ST",
    "SCMN.SW", "SEB-A.ST", "SHL.DE", "SIE.DE", "SLA.L",
    "SLHN.SW", "SOI.PA", "SREN.SW", "STERV.HE", "STM.MI",
    "STMN.SW", "SU.PA", "SW.PA", "SY1.DE", "SZG.DE",
    "TIT.MI", "TIETO.HE", "TSCO.L", "UBSG.SW", "UCB.BR",
    "UN0.DE", "UNI3.MC", "UPM.HE", "VIE.PA", "VIS.MC",
    "VOLV-B.ST", "VOW.DE", "WPP.L", "ZAL.DE",
]


def fresh_universe() -> list[str]:
    """De-dup against any tickers we already have processed."""
    return sorted(set(BROADER_UNIVERSE))
